public class XSS_Mitigations_Challenge {
    
    public string sampleMergeField1 {
        get {
            return '<i>TEST DATA1</i>';
        }
        set;
    }
    
    public string sampleMergeField2 {
        get {
            return '<i>TEST DATA2</i>';
        }
        set;
    }
    
    public string sampleMergeField3 {
        get {
            return '<i>TEST DATA3</i>';
        }
        set;
    }
    
    public string sampleMergeField4 {
        get {
            return '<i>TEST DATA4</i>';
        }
        set;
    }
    
    public string sampleMergeField5 {
        get {
            return '<i>TEST DATA5</i>';
        }
        set;
    }
    
    public string sampleMergeField6 {
        get {
            return '<i>TEST DATA6</i>';
        }
        set;
    }
    
    public string sampleMergeField7 {
        get {
            return '<i>TEST DATA7</i>';
        }
        set;
    }
    
}